In [1]:
import numpy as np

In [2]:
list = ['1','2','3','4','5']
array_list = np.array(object = list)

In [3]:
list

['1', '2', '3', '4', '5']

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [8]:
#Q1 array represents a fixed-size, 
# homogeneous collection of elements. Unlike lists, arrays can only store elements of the same data type.
type(list)

list

In [9]:
type(array_list)

numpy.ndarray

In [13]:
#Q2
# for list
for i in list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [15]:
# for array_list
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [17]:
#Q3
array_list = np.array(object = list, dtype = int)
array_list

array([1, 2, 3, 4, 5])

In [18]:
# for list
for i in list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [19]:
# for array_list
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


in list each element of list is of string datatype while in array_list each element is of int datatype

In [20]:
#Q4
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [21]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [22]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.shape(num_array)

(2, 3)

In [24]:
np.size(num_array)

6

In [27]:
#Q5
arr1 = np.zeros((3,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
#Q6
arr2 = np.eye(5)
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])